### ISSUE TITLE
CHM文件报错'gbk' codec can't decode

### ISSUE THREAD

**Issue by LianSchedule** [mnt-ltd/moredoc#21]
一个中文的CHM文件报错，我已经把中文包都装上了
```
in _create_html_root UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 1023
```
下面是全部的报错内容
```
exit status 1 Sandboxing disabled by user. qt.webenginecontext: GL Type: disabled Surface Type: DefaultRenderableType Surface Profile: NoProfile Surface Version: 2.0 QSG RHI Backend: OpenGL Using Supported QSG Backend: yes Using Software Dynamic GL: no Using Multithreaded OpenGL: no Init Parameters: * application-name ebook-convert * browser-subprocess-path /opt/calibre/libexec/QtWebEngineProcess * disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture * disable-gpu * disable-speech-api * enable-features NetworkServiceInProcess,TracingServiceInProcess * enable-threaded-compositing * in-process-gpu * no-sandbox * use-gl disabled Traceback (most recent call last): File "runpy.py", line 196, in _run_module_as_main File "runpy.py", line 86, in _run_code File "site.py", line 47, in <module> File "site.py", line 43, in main File "calibre/ebooks/conversion/cli.py", line 419, in main File "calibre/ebooks/conversion/plumber.py", line 1108, in run File "calibre/customize/conversion.py", line 242, in __call__ File "calibre/ebooks/conversion/plugins/chm_input.py", line 76, in convert File "calibre/ebooks/conversion/plugins/chm_input.py", line 117, in _create_html_root UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 1023: illegal multibyte sequence Conversion options changed from defaults: pdf_page_margin_left: 36.0 pdf_page_margin_bottom: 36.0 pdf_page_margin_right: 36.0 paper_size: 'a4' pdf_page_margin_top: 36.0 1% Converting input to HTML... InputFormatPlugin: CHM Input running on /www/wwwroot/moredoc/cache/convert/2023/08/02/5c76bbee-457d-47a8-b179-f30b3bf3a829/3c0d42a33be97f5f99e02a261928a9f2.chm
```

**Comment by TruthHun** [comment]
这种属于calibre的问题，我们无法解决
